# Generated by Django 6.0.3 on 2026-03-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=500)),
                ('timeAgo', models.TimeField(auto_now=True)),
                ('category', models.CharField()),
            ],
        ),
    ]
