# Generated by Django 6.0.3 on 2026-03-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='post',
            new_name='post_id',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='upvote',
        ),
        migrations.AddField(
            model_name='post',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='reactions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='post',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Upvote'), (-1, 'Downvote')], null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='reaction',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('love', 'Love'), ('laugh', 'Laugh'), ('angry', 'Angry')], max_length=20, null=True),
        ),
    ]
