# Generated by Django 6.0.3 on 2026-03-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_post_vote_post_id_remove_vote_downvote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hot_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='post',
            name='trending_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='vote',
            name='reaction',
            field=models.CharField(blank=True, choices=[('haha', 'haha'), ('relatable', 'relatable'), ('wtf', 'wtf'), ('ughh', 'ughh'), ('seriously', 'seriously')], max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user_id', 'post_id')},
        ),
    ]
